// Validador de Clientes
// Este script valida clientes com base em suas compras recentes para posteriormente segmentar os clientes baseado em quem captou o Lead.

WITH CTE AS (SELECT 
	D2_CLIENTE,
	D2_LOJA,
	F2_EMISSAO,
    DATEDIFF(DAY,CAST(LEAD(F2_EMISSAO, 1) OVER (PARTITION BY F2_CLIENTE ORDER BY CAST(F2_EMISSAO AS DATE) DESC) AS DATE) , CAST(F2_EMISSAO AS DATE)) COMPRAS_DIFERENCA_DIA
FROM SD2010 SD2
INNER JOIN SF2010 SF2 ON F2_FILIAL = D2_FILIAL
    AND F2_CLIENTE = D2_CLIENTE
    AND F2_LOJA = D2_LOJA
    AND F2_DOC = D2_DOC
    AND F2_SERIE = D2_SERIE
    AND SF2.D_E_L_E_T_ = ' '
WHERE D2_EMISSAO >= '20230101'
    AND D2_TIPO NOT IN ('B', 'D')
    AND SD2.D_E_L_E_T_ = ' '
	AND SD2.D_E_L_E_T_ = '')


SELECT DISTINCT D2_CLIENTE, D2_LOJA, A1_CGC, A1_NOME,
CASE WHEN A1_PRICOM >= DATEADD(MONTH, -1, GETDATE()) THEN 'POSITIVADO'
WHEN COMPRAS_DIFERENCA_DIA >= 90 THEN 'REPOSITIVADO' END AS STATUS
FROM CTE
INNER JOIN SA1010 SA1 ON A1_COD = D2_CLIENTE AND A1_LOJA = D2_LOJA AND A1_FILIAL = '01' AND SA1.D_E_L_E_T_ = ''
WHERE (COMPRAS_DIFERENCA_DIA >= 90 OR A1_PRICOM >= DATEADD(MONTH, -1, GETDATE())) AND F2_EMISSAO >= DATEADD(MONTH, -2, GETDATE())
AND A1_CGC IN (
    "CNPJS"
)
