SELECT 
    'P |01|SA1010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL,' ')) + '|' + RTRIM(COALESCE(A1_COD,' ')) + RTRIM(COALESCE(A1_LOJA,' ')),' '), '|') AS PK_CLIENTE,
	A1_CGC CNPJ,
	A1_DDD + '-' + A1_TEL TELEFONE,
    SA1.A1_COD AS COD_CLIENTE,
    SA1.A1_LOJA AS LOJA_CLIENTE,
    SA1.A1_NOME AS NOME_CLIENTE,
	SA1.A1_COMIS AS COMISSAO,
	SA1.A1_AJCUSTO AS AJUDA_CUSTO,
    SA1.A1_SATIV1 AS SEGMENTACAO_ATIVIDADE_1,
    SA1.A1_SATIV5 AS SEGMENTACAO_ATIVIDADE_5,
    SA1.A1_SATIV8 AS SEGMENTACAO_ATIVIDADE_8,
	A1_CODSEG COD_SEGMENTO,
	A1_EMAIL EMAIL,

    CASE
	WHEN LTRIM(RTRIM(A1_PRICOM)) = '' THEN ''
	ELSE A1_PRICOM
    END AS PRIMEIRA_COMPRA,

    CASE
	WHEN LTRIM(RTRIM(A1_ULTCOM)) = '' THEN ''
	ELSE A1_ULTCOM
    END AS ULTIMA_COMPRA,

    CASE 
    	WHEN DATEDIFF(DAY, CAST(A1_ULTCOM AS DATE), CAST(GETDATE() AS DATE)) >= 90 THEN 'INATIVO'
   	ELSE 'ATIVO' 
    END AS STATUS,

	CASE WHEN A1_ULTCOM = '' THEN ''
	ELSE TRIM(CONVERT(VARCHAR(8),DATEADD(DAY, 90, A1_ULTCOM),112)) END AS MES_INATIVO,
	'P |01|SA3010|' + COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL, ' ')) + '|' + RTRIM(COALESCE(A3_COD, ' ')), ' '), '|') AS PK_VENDEDOR,
	A1_MUN MUNICIPIO,
	A1_BAIRROE BAIRRO
FROM 
    SA1010 SA1 
LEFT JOIN SA3010 SA3 ON A3_FILIAL = A1_FILIAL
AND A1_VEND = A3_COD
AND SA3.D_E_L_E_T_ = ''
WHERE  
    SA1.D_E_L_E_T_ = ' '  


