SELECT
	'01' AS INSTANCIA,
	D2_FILIAL AS FILIAL,
    F2_SERIE AS SERIE_DA_NOTA_FISCAL,
    F2_DOC AS NUMERO_DA_NOTA_FISCAL,
    D2_PEDIDO AS NUMERO_PEDIDO_VENDA,
    D2_ITEM AS NUMERO_ITEM,
    CASE
        WHEN LTRIM(RTRIM(F2_EMISSAO)) = ' ' THEN ' '
        ELSE F2_EMISSAO
    END AS DATA_DE_EMISSAO,
    CASE
        WHEN LTRIM(RTRIM(F2_EMINFE)) = ' ' THEN ' '
        ELSE F2_EMINFE
    END AS DATA_SAIDA_NF,
    F2_TPFRETE AS TIPO_DE_FRETE,
    D2_TIPO AS TIPO_DE_NOTA_FISCAL,
    D2_ORIGLAN AS ORIGEM_DO_LANCAMENTO
FROM SD2010 SD2
INNER JOIN SF2010 SF2 ON F2_FILIAL = D2_FILIAL
    AND F2_CLIENTE = D2_CLIENTE
    AND F2_LOJA = D2_LOJA
    AND F2_DOC = D2_DOC
    AND F2_SERIE = D2_SERIE
    AND SF2.D_E_L_E_T_ = ' '
WHERE D2_EMISSAO  BETWEEN  <<START_DATE>> AND <<FINAL_DATE>>
    AND D2_TIPO NOT IN ('B', 'D')
    AND SD2.D_E_L_E_T_ = ' '
ORDER BY F2_DOC;
