SELECT 
'P |01|SB1010|'+ COALESCE(NULLIF(RTRIM( COALESCE(B1_FILIAL,' ') )+'|'+RTRIM( COALESCE(B1_COD,' ') ),' '),'|') AS PK_PRODUTO
,SB1.B1_COD AS COD_ITEM
,SB1.B1_DESC AS DESC_ITEM
,SB1.B1_POSIPI AS CLASSIFICACAO_FISCAL
,SB1.B1_COMIS AS COMISSAO,
SB1.B1_AJCUSTO AS AJUDA_CUSTO
,CASE 
WHEN SB1.B1_MSBLQL = 2 THEN 'NAO'
WHEN SB1.B1_MSBLQL = 1 THEN 'SIM'
END AS ITEM_BLOQ
FROM SB1010 SB1 
WHERE SB1.D_E_L_E_T_ = ''
UNION 
SELECT 
'P |01|SB1010||'
,'01 - INDEFINIDO'
,'01 - INDEFINIDO'
,'01 - INDEFINIDO'
,0
,0
,'01 - INDEFINIDO'
