SELECT 
    CASE 
        WHEN D1_FILIAL IS NULL THEN 'P |01||' 
        ELSE 'P |01|01' + CAST(D1_FILIAL AS CHAR(6)) 
    END AS PK_FILIAL,
    D1_DTDIGIT AS DATA_DE_DEVOLUCAO,
    D1_SERIE AS SERIE_DOCUMENTO_CLIENTE,
    D1_DOC AS NUMERO_DOCUMENTO_CLIENTE,
    F2_SERIE AS SERIE_NOTA_FISCAL,
    F2_DOC AS NUMERO_DA_NOTA_FISCAL,
    D1_ITEM AS NUMERO_DO_ITEM_DO_DOCUMENTO,
    D1_DOC + D1_SERIE AS NUMERO_DO_ITEM_DA_NF,
    D1_REMITO AS NUMERO_DO_REMITO,
    D1_SERIREM AS SERIE_DO_REMITO,
    D1_ITEMREM AS ITEM_DO_REMITO,
    'P |01|SF4010|' + COALESCE(NULLIF(RTRIM(COALESCE(F4_FILIAL,' ')) + '|' + RTRIM(COALESCE(D1_TES,' ')), ' '), '|') AS PK_TES,
    'P |01|SB1010|' + COALESCE(NULLIF(RTRIM(COALESCE(B1_FILIAL,' ')) + '|' + RTRIM(COALESCE(D1_COD,' ')), ' '), '|') AS PK_PRODUTO,
    'P |01|SA3010|' + COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL,' ')) + '|' + RTRIM(COALESCE(F2_VEND1,' ')), ' '), '|') AS PK_VENDEDOR,
    'P |01|SA1010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL,' ')) + '|' + RTRIM(COALESCE(D1_FORNECE,' ')) + RTRIM(COALESCE(D1_LOJA,' ')), ' '), '|') AS PK_CLIENTE,
    CASE 
        WHEN SA1.A1_COD_MUN = ' ' THEN 'P |01|CC2010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_EST,' ')), ' '), '|')
        ELSE 'P |01|CC2010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_EST,' ')) + RTRIM(COALESCE(A1_COD_MUN,' ')), ' '), '|')
    END AS PK_REGIAO,
    D1_QUANT AS QTDE_DEVOLVIDA_ITEM,
    D1_TOTAL + D1_VALIPI + D1_ICMSRET AS VL_DEVOLUCAO_TOTAL,
    D1_VALICM AS VL_ICMS_DEVOLUCAO,
    D1_VALIPI AS VL_IPI_DEVOLUCAO,
    (D1_TOTAL - (D1_VALICM + D1_VALIMP5 + D1_VALIMP6 + D1_VALDESC)) AS VL_DEVOLUCAO_LIQUIDA,
    D1_TOTAL - D1_VALDESC AS VL_DEVOLUCAO_MERCADORIA,
    D1_VALIMP6 AS VL_PIS_DEVOLUCAO,
    D1_VALIMP5 AS VL_COFINS_DEVOLUCAO,
    D1_ICMSRET AS VL_ICMS_SUBST_DEVOLUCAO,
    D1_VALDESC AS VL_DESCONTO_DEVOLUCAO,
    D1_VALINS AS VL_INSS_DEVOLUCAO
FROM 
    SD1010 SD1
INNER JOIN 
    SF2010 SF2 ON SF2.D_E_L_E_T_ = ' ' 
               AND F2_FILIAL = D1_FILIAL 
               AND F2_DOC = D1_NFORI 
               AND F2_SERIE = D1_SERIORI 
               AND F2_CLIENTE = D1_FORNECE 
               AND F2_LOJA = D1_LOJA
INNER JOIN 
    SB1010 SB1 ON B1_FILIAL = SUBSTRING(F2_FILIAL, 1, 2) 
               AND SB1.B1_COD = D1_COD 
               AND SB1.D_E_L_E_T_ = ' '
LEFT JOIN 
    SF4010 SF4 ON F4_FILIAL = SUBSTRING(D1_FILIAL, 1, 2) 
                AND D1_TES = F4_CODIGO 
                AND SF4.D_E_L_E_T_ = ' '
LEFT JOIN 
    SE4010 SE4 ON E4_FILIAL = SUBSTRING(D1_FILIAL, 1, 2) 
                AND E4_CODIGO = F2_COND 
                AND SE4.D_E_L_E_T_ = ' '
LEFT JOIN 
    SA3010 SA3 ON A3_FILIAL = SUBSTRING(F2_FILIAL, 1, 2) 
                AND A3_COD = SF2.F2_VEND1 
                AND SA3.D_E_L_E_T_ = ' '
LEFT JOIN 
    SA1010 SA1 ON A1_FILIAL = SUBSTRING(F2_FILIAL, 1, 2) 
                AND SA1.A1_COD = SF2.F2_CLIENTE 
                AND SA1.A1_LOJA = SF2.F2_LOJA 
                AND SA1.D_E_L_E_T_ = ' '

 
WHERE  
     D1_DTDIGIT >= '20230101' AND A1_SATIV8 = '000907'
    AND SD1.D_E_L_E_T_ = ' '
