SELECT 
    CASE
        WHEN D2_FILIAL IS NULL THEN 'P |01||'
        ELSE 'P |01|01' + CAST(D2_FILIAL AS CHAR(6))
    END AS PK_FILIAL,
    F2_SERIE AS SERIE_DA_NOTA_FISCAL,
    F2_DOC AS NUMERO_DA_NOTA_FISCAL,
    D2_PEDIDO AS NUMERO_PEDIDO_VENDA,
    D2_ITEM AS NUMERO_ITEM,
    CASE
    WHEN LTRIM(RTRIM(F2_EMISSAO)) = ' ' THEN ' '
    ELSE F2_EMISSAO
    END AS DATA_DE_EMISSAO,
    CASE
    WHEN LTRIM(RTRIM(F2_EMINFE)) = ' ' THEN ' '
    ELSE F2_EMINFE
    END AS DATA_SAIDA_NF,
    DATEDIFF(DAY,CAST(LEAD(F2_EMISSAO, 1) OVER (PARTITION BY F2_CLIENTE ORDER BY CAST(F2_EMISSAO AS DATE) DESC) AS DATE) , CAST(F2_EMISSAO AS DATE)) COMPRAS_DIFERENCA_DIA,
    F2_TPFRETE AS TIPO_DE_FRETE,
    D2_TIPO AS TIPO_DE_NOTA_FISCAL,
    D2_ORIGLAN AS ORIGEM_DO_LANCAMENTO,
    'P |01|SB1010|' + COALESCE(NULLIF(RTRIM(COALESCE(B1_FILIAL, ' ')) + '|' + RTRIM(COALESCE(D2_COD, ' ')), ' '), '|') AS PK_PRODUTO,
    'P |01|SA3010|' + COALESCE(NULLIF(RTRIM(COALESCE(A3_FILIAL, ' ')) + '|' + RTRIM(COALESCE(F2_VEND1, ' ')), ' '), '|') AS PK_VENDEDOR,
    'P |01|SF4010|' + COALESCE(NULLIF(RTRIM(COALESCE(F4_FILIAL, ' ')) + '|' + RTRIM(COALESCE(D2_TES, ' ')), ' '), '|') AS PK_TES,
    'P |01|SA1010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_FILIAL, ' ')) + '|' + RTRIM(COALESCE(D2_CLIENTE, ' ')) + RTRIM(COALESCE(D2_LOJA, ' ')), ' '), '|') AS PK_CLIENTE,
    CASE
        WHEN A1_COD_MUN = ' ' THEN 'P |01|CC2010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' ')), ' '), '|')
        ELSE 'P |01|CC2010|' + COALESCE(NULLIF(RTRIM(COALESCE(A1_EST, ' ')) + RTRIM(COALESCE(A1_COD_MUN, ' ')), ' '), '|')
    END AS PK_REGIAO,
    'P |01|SE4010|' + COALESCE(NULLIF(RTRIM(COALESCE(E4_FILIAL, ' ')) + '|' + RTRIM(COALESCE(F2_COND, ' ')), ' '), '|') AS PK_CONDICAO_DE_PAGAMENTO,
    CAST(COALESCE(D2_VALBRUT, 0) AS DECIMAL(14, 2)) AS VL_FATURAMENTO_TOTAL,
    CAST(COALESCE(D2_VALICM, 0) AS DECIMAL(14, 2)) AS VL_ICMS_FATURAMENTO,
    CAST(COALESCE(D2_VALIPI, 0) AS DECIMAL(14, 2)) AS VL_IPI_FATURAMENTO,
    CAST(COALESCE(D2_VALFRE, 0) AS DECIMAL(14, 2)) AS VL_FRETE_NF,
    CAST(COALESCE(D2_DESPESA, 0) AS DECIMAL(14, 2)) AS VL_DESPESA,
    CAST(COALESCE(D2_TOTAL, 0) AS DECIMAL(14, 2)) AS VL_FATURAMENTO_MERCADORIA,
    CAST(COALESCE(D2_VALIMP6, 0) AS DECIMAL(14, 2)) AS VL_PIS_FATURAMENTO,
    CAST(COALESCE(D2_VALIMP5, 0) AS DECIMAL(14, 2)) AS VL_COFINS_FATURAMENTO,
    CAST(COALESCE(D2_QUANT, 0) AS DECIMAL(12, 4)) AS QTD_FATURADA_ITEM,
    CAST(COALESCE(D2_VALISS, 0) AS DECIMAL(14, 2)) AS VL_ISS_FATURAMENTO,
    CAST(COALESCE(D2_ICMSRET, 0) AS DECIMAL(14, 2)) AS VL_ICMS_SUBST_FATURAMENTO,
    CAST(COALESCE(D2_DESCON, 0) AS DECIMAL(12, 2)) AS VL_DESCONTO_FATURAMENTO,
    CAST(COALESCE(D2_VALIRRF, 0) AS DECIMAL(14, 2)) AS VL_IRF_FATURAMENTO,
    CAST(COALESCE(D2_VALINS, 0) AS DECIMAL(14, 2)) AS VL_INSS_FATURAMENTO,
    CAST(COALESCE(D2_PESO * D2_QUANT, 0) AS DECIMAL(12, 4)) AS PESO_LIQUIDO,
    CAST(COALESCE(B1_PESBRU * D2_QUANT, 0) AS DECIMAL(12, 4)) AS PESO_BRUTO,
    1 AS QTD,
    CAST(COALESCE(D2_PRUNIT, 0) AS DECIMAL(14, 4)) AS VL_UNITARIO,
    CAST(COALESCE(D2_SEGURO, 0) AS DECIMAL(14, 2)) AS VL_SEGURO
FROM SD2010 SD2
INNER JOIN SF2010 SF2 ON F2_FILIAL = D2_FILIAL
    AND F2_CLIENTE = D2_CLIENTE
    AND F2_LOJA = D2_LOJA
    AND F2_DOC = D2_DOC
    AND F2_SERIE = D2_SERIE
    AND SF2.D_E_L_E_T_ = ' '
INNER JOIN SB1010 SB1 ON B1_FILIAL = SUBSTRING(D2_FILIAL, 1, 2)
    AND SB1.B1_COD = SD2.D2_COD
    AND SB1.D_E_L_E_T_ = ' '
INNER JOIN SF4010 SF4 ON F4_FILIAL = SUBSTRING(D2_FILIAL, 1, 2)
    AND SF4.F4_CODIGO = SD2.D2_TES
    AND SF4.D_E_L_E_T_ = ' '
LEFT JOIN SA1010 SA1 ON A1_FILIAL = SUBSTRING(D2_FILIAL, 1, 2)
    AND SA1.A1_COD = SF2.F2_CLIENTE
    AND SA1.A1_LOJA = SF2.F2_LOJA
    AND SA1.D_E_L_E_T_ = ' '
LEFT JOIN SA3010 SA3 ON A3_FILIAL = SUBSTRING(D2_FILIAL, 1, 2)
    AND A3_COD = F2_VEND1
    AND SA3.D_E_L_E_T_ = ' '
LEFT JOIN SE4010 SE4 ON E4_FILIAL = SUBSTRING(D2_FILIAL, 1, 2)
    AND E4_CODIGO = F2_COND
    AND SE4.D_E_L_E_T_ = ' '
WHERE A1_SATIV8 = '000907' AND D2_EMISSAO >= '20230101'
    AND D2_TIPO NOT IN ('B', 'D')
    AND SD2.D_E_L_E_T_ = ' '
ORDER BY F2_DOC;
